### PR TITLE
Responsive console

### PR DESCRIPTION
**Pull request by balihoo-aharl**
I've made the console responsive. We will likely want to address how it functions on small screens and optimize the interaction for phones and small tablets in the future as well.

### CODE REVIEW

**Comment by balihoo-aharl** [comment]
@balihoo-pprice I fixed some upstream conflicts on this pull request so it can be merged again. I apologize for the duplicate commits. I had assumed that Github would play nice with rebasing the commits to change the author.

**Comment by balihoo-pprice** [comment]
Hi @balihoo-aharl . Sorry for the slow response on this merge request, it has been a busy few days. I'm testing this locally and the new styling looks fine except when I'm on my laptop. My laptop has limited vertical resolution, and now that the panel is much taller it takes up 1/5th of my usable real-estate which makes reviewing the local site content itself very cramped. The idea was to have a very slim console so that it wasn't as noticeable or hoggish of the space allocated to the actual site design.
Can you rework font-sizes, margin and padding to get it back to an ultra-slim footprint? Thanks.

**Comment by balihoo-aharl** [comment]
@balihoo-pprice I've made the console toolbar smaller than it was before and I added media queries to handle screens smaller than 800px wide.

**Comment by balihoo-pprice** [comment]
Thanks @balihoo-aharl . I'm still seeing some things that don't size down when as the page shrinks up. For example, the big margins and padding around buttons and some of the text (e.g. test results). Here's an example:
selection_034

**Comment by balihoo-aharl** [comment]
@balihoo-pprice what browser are you using?

**Comment by balihoo-pprice** [comment]
Chrome on Ubuntu

**Comment by balihoo-aharl** [comment]
@balihoo-pprice, taking a closer look at your screenshot, it looks like your laptop is around 600px wide(?). I'm thinking that for very small screens we will want to use media queries to create a "drawer" like interaction to hide and show a pane which slides in from the top of the screen. We could have a small "handle" at the top that has a red or green indicator for tests passing or a failure, but more info would be available in the "drawer".

The alternative is to make the type very very small and have a less than ideal layout on smaller screens.

If you would like I can work all that into this pull request or we can address the more advanced interaction in another pull request.

**Comment by balihoo-pprice** [comment]
Another pull request would be fine. I'm going to merge this one.

On Thu, Jan 15, 2015 at 1:41 PM, balihoo-aharl notifications@github.com
wrote:

> @balihoo-pprice https://github.com/balihoo-pprice, taking a closer look
> at your screenshot, I'm thinking that for very small screens we will want
> to use media queries to create a "drawer" like interaction to hide and show
> a pane which slides in from the top of the screen. We could have a small
> "handle" at the top that has a red or green indicator for tests passing or
> a failure, but more info would be available in the "drawer".
> 
> The alternative is to make the type very very small and have a less than
> ideal layout on smaller screens.
> 
> If you would like I can work all that into this pull request or we can
> address the more advanced interaction in another pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/balihoo/balihoo-creative/pull/1#issuecomment-70157692
> .

## 

Paul Price | CTO, Balihoo | http://balihoo.com | c: 208-284-3853 | p:
208-656-7729

**Pull request merged**
